// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// //import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBU8_vfa6-jU3K9YNQnoiJ57QIX8o7df8M',
//     appId: '1:228515794918:web:70e5bf5122e6f2df30d027',
//     messagingSenderId: '228515794918',
//     projectId: 'schedule-tracker-664fc',
//     authDomain: 'schedule-tracker-664fc.firebaseapp.com',
//     storageBucket: 'schedule-tracker-664fc.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAwlVdE_8I6TW3SUgeOPfcRv-fWfCc8eSw',
//     appId: '1:228515794918:android:b12e162923ebed2e30d027',
//     messagingSenderId: '228515794918',
//     projectId: 'schedule-tracker-664fc',
//     storageBucket: 'schedule-tracker-664fc.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDskpad_ga1bK2lyCKkz5YFGQ_makDCJEA',
//     appId: '1:228515794918:ios:8b983105b1e8b6ee30d027',
//     messagingSenderId: '228515794918',
//     projectId: 'schedule-tracker-664fc',
//     storageBucket: 'schedule-tracker-664fc.appspot.com',
//     iosClientId: '228515794918-n7aq39i7leasqlgkrigk2r2nmu8hg54c.apps.googleusercontent.com',
//     iosBundleId: 'com.example.project',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDskpad_ga1bK2lyCKkz5YFGQ_makDCJEA',
//     appId: '1:228515794918:ios:8b983105b1e8b6ee30d027',
//     messagingSenderId: '228515794918',
//     projectId: 'schedule-tracker-664fc',
//     storageBucket: 'schedule-tracker-664fc.appspot.com',
//     iosClientId: '228515794918-n7aq39i7leasqlgkrigk2r2nmu8hg54c.apps.googleusercontent.com',
//     iosBundleId: 'com.example.project',
//   );
// }
